AWSTemplateFormatVersion: "2010-09-09"
Description: CICD pipelines to automate SDLF workflows

Parameters:
  pArtifactsBucket:
    Description: The artifacts bucket used by CodeBuild and CodePipeline
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/S3/DevOpsArtifactsBucket
  pKMSKey:
    Description: The KMS key used by CodeBuild and CodePipeline
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/KMS/CICDKeyId

Resources:
  rBuildCloudformationModuleRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: The actions with "*" are all ones that only support the all resources wildcard
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: sdlf-cicd-build-cfn-module-codebuild
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:ValidateTemplate # W11 exception
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/sdlf-*
              - Effect: Allow
                Action:
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                Resource:
                  - !Sub arn:${AWS::Partition}:s3:::${pArtifactsBucket}/*
              - Effect: Allow
                Action:
                  - kms:CreateGrant
                  - kms:Decrypt
                  - kms:DescribeKey
                  - kms:Encrypt
                  - kms:GenerateDataKey*
                  - kms:ReEncrypt*
                Resource:
                  - !Ref pKMSKey
              - Effect: Allow
                Action:
                  - ssm:GetParametersByPath
                Resource: !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/SDLF/Misc/Domains/*
              - Effect: Allow
                Action: sts:AssumeRole
                Resource: !Sub arn:${AWS::Partition}:iam::*:role/sdlf-cicd-domain-crossaccount-cfn-modules

  rBuildCloudformationModuleStage:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: sdlf-cicd-build-cfn-module
      Artifacts:
        Type: CODEPIPELINE
      Description: Build a CloudFormation module from Serverless templates
      EncryptionKey: !Ref pKMSKey
      Environment:
        EnvironmentVariables:
          - Name: ARTIFACTS_BUCKET
            Type: PLAINTEXT
            Value: !Ref pArtifactsBucket
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        Type: LINUX_CONTAINER
      QueuedTimeoutInMinutes: 60
      ServiceRole: !Ref rBuildCloudformationModuleRole
      Source:
        BuildSpec: !Sub |
          version: 0.2
          phases:
            install:
              runtime-versions:
                python: 3.11
              commands:
                - |-
                    pip3 uninstall -y aws-sam-cli
                    aws s3api get-object --bucket "$ARTIFACTS_BUCKET" --key aws-sam-cli-linux-x86_64.zip aws-sam-cli-linux-x86_64.zip \
                    && unzip -q aws-sam-cli-linux-x86_64.zip -d sam-installation
                    ./sam-installation/install \
                    && sam --version
                - pip3 install cloudformation-cli
                - aws s3api get-object --bucket "$ARTIFACTS_BUCKET" --key sam-translate.py sam-translate.py
            build:
              commands:
                - sam package --template-file ./template.yaml --s3-bucket "$ARTIFACTS_BUCKET" --s3-prefix sdlf --output-template-file template.yaml
                - python3 sam-translate.py --template-file=template.yaml --output-template=translated-template.json
                - |-
                    aws s3api put-object --bucket "$ARTIFACTS_BUCKET" \
                      --key "modules/$DOMAIN_NAME/$ENVIRONMENT/$TEAM_NAME/translated-template.json" \
                      --body translated-template.json
                    TEMPLATE_URL=$(aws s3 presign "s3://$ARTIFACTS_BUCKET/modules/$DOMAIN_NAME/$ENVIRONMENT/$TEAM_NAME/translated-template.json" --expires-in 300)
                    aws cloudformation validate-template --template-url "$TEMPLATE_URL"
                - |-
                    DOMAIN_ACCOUNTS=$(aws ssm get-parameters-by-path --path "/SDLF/Misc/Domains/" --recursive --query "Parameters[?contains(Name, '/$ENVIRONMENT/AccountId')].Value" --output text)
                    echo "Domain accounts found - $DOMAIN_ACCOUNTS"
                - |-
                    mkdir module
                    cd module || exit
                    cfn init --artifact-type MODULE --type-name "$DOMAIN_NAME::$TEAM_NAME::$MODULE_NAME::MODULE" && rm fragments/sample.json
                    cp -i -a ../translated-template.json fragments/
                    cfn generate
                    zip --quiet -r "../$MODULE_NAME.zip" .rpdk-config fragments/ schema.json

                    NEW_MODULE="$CODEBUILD_RESOLVED_SOURCE_VERSION"
                    aws s3api put-object --bucket "$ARTIFACTS_BUCKET" \
                                          --key "modules/$DOMAIN_NAME/$ENVIRONMENT/$TEAM_NAME/$MODULE_NAME-$NEW_MODULE.zip" \
                                          --body "../$MODULE_NAME.zip"
                - |-
                    for DOMAIN_ACCOUNT_ID in $DOMAIN_ACCOUNTS; do
                        temp_role=$(aws sts assume-role --role-arn "arn:${AWS::Partition}:iam::$DOMAIN_ACCOUNT_ID:role/sdlf-cicd-domain-crossaccount-cfn-modules" --role-session-name "codebuild-cfn-module")
                        AWS_ACCESS_KEY_ID=$(echo "$temp_role" | jq .Credentials.AccessKeyId | xargs)
                        AWS_SECRET_ACCESS_KEY=$(echo "$temp_role" | jq .Credentials.SecretAccessKey | xargs)
                        AWS_SESSION_TOKEN=$(echo "$temp_role" | jq .Credentials.SessionToken | xargs)
                        export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN

                        # compare hashes to avoid creating a new module version when there is no change
                        if CURRENT_MODULE=$(aws ssm get-parameter --name "/SDLF/CFN/$DOMAIN_NAME-$TEAM_NAME-$MODULE_NAME-MODULE" --query "Parameter.Value" --output text); then
                          echo "Current module version commit id: $CURRENT_MODULE"
                          echo "New module version commit id: $NEW_MODULE"
                          if [ "$NEW_MODULE" == "$CURRENT_MODULE" ]; then
                            echo "No change since last build, exiting module creation."
                            exit 0
                          fi
                        fi

                        STACK_NAME="sdlf-cfn-module-$TEAM_NAME-$MODULE_NAME"
                        aws cloudformation deploy \
                            --stack-name "$STACK_NAME" \
                            --template-file "$CODEBUILD_SRC_DIR_SourceCicdArtifact"/template-cfn-module.yaml \
                            --parameter-overrides \
                                pArtifactsBucket="$ARTIFACTS_BUCKET" \
                                pEnvironment="$ENVIRONMENT" \
                                pDomain="$DOMAIN_NAME" \
                                pTeamName="$TEAM_NAME" \
                                pModuleName="$MODULE_NAME" \
                                pModuleGitRef="$NEW_MODULE" \
                            --tags Framework=sdlf \
                            --capabilities "CAPABILITY_NAMED_IAM" "CAPABILITY_AUTO_EXPAND" \
                            --role-arn "arn:${AWS::Partition}:iam::$DOMAIN_ACCOUNT_ID:role/sdlf-cicd-cfn-modules" || exit 1
                        echo "done for $DOMAIN_ACCOUNT_ID"
                    done
                - cd .. && rm -Rf module
          artifacts:
            files:
              - "*"
              - "**/*"
        Type: CODEPIPELINE
      TimeoutInMinutes: 5

  ######## SSM OUTPUTS #########
  rBuildCloudformationModuleStageSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeBuild/BuildCloudformationModuleStage
      Type: String
      Value: !Ref rBuildCloudformationModuleStage
      Description: Name of the CodeBuild job that build a CloudFormation module from a SAM template

Outputs:
  oBuildCloudformationModuleStageArn:
    Description: The ARN of the CloudFormation module CodeBuild job
    Value: !GetAtt rBuildCloudformationModuleStage.Arn
