AWSTemplateFormatVersion: 2010-09-09
Description: Glue Job Sample

Parameters:
  pDatasetName:
    Description: The dataset name
    Type: String
    Default: legislators
  pArtifactsBucket:
    Description: The artifactory bucket used by CodeBuild and CodePipeline
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/S3/ArtifactsBucket
  pTeamName:
    Description: The team name
    Type: String
    Default: engineering
  pEnableVpc:
    Description: Deploy SDLF resources in a VPC
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/VPC/Enabled

Conditions:
  RunInVpc: !Equals [!Ref pEnableVpc, true]

Resources:
  rGlueRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSGlueServiceRole
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonS3FullAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: !Sub sdlf-${pTeamName}-${pDatasetName}-glue-job
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - kms:CreateGrant
                  - kms:Decrypt
                  - kms:DescribeKey
                  - kms:Encrypt
                  - kms:GenerateDataKey*
                  - kms:ReEncrypt*
                Resource:
                  - !Sub "{{resolve:ssm:/SDLF/KMS/${pTeamName}/InfraKeyId:1}}"
                  - !Sub "{{resolve:ssm:/SDLF/KMS/${pTeamName}/DataKeyId:1}}"
                  - "{{resolve:ssm:/SDLF/KMS/KeyArn:1}}"

  rGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        PythonVersion: "3"
        ScriptLocation: !Sub s3://${pArtifactsBucket}/artifacts/${pDatasetName}-glue-job.py
      DefaultArguments: !If
        - RunInVpc
        -
          "--job-bookmark-option": job-bookmark-enable
          "--enable-metrics": ""
          "--disable-proxy-v2": "true"
        -
          "--job-bookmark-option": job-bookmark-enable
          "--enable-metrics": ""
      ExecutionProperty:
        MaxConcurrentRuns: 3
      MaxRetries: 0
      MaxCapacity: 2.0
      GlueVersion: "4.0"
      Name: !Sub sdlf-${pTeamName}-${pDatasetName}-glue-job
      SecurityConfiguration: !Sub sdlf-${pTeamName}-glue-security-config
      Role: !Ref rGlueRole
