AWSTemplateFormatVersion: 2010-09-09
Description: Example datasets

Parameters:
    pPipelineReference:
        Type: String
        Default: none

Resources:
    rLegislators:
        Type: awslabs::sdlf::dataset::MODULE
        Properties:
            pPipelineReference: !Ref pPipelineReference
            pDatasetName: legislators
            pS3Prefix: legislators
            pDeploymentInstance: dev
            pStorageDeploymentInstance: dev
