AWSTemplateFormatVersion: "2010-09-09"
Description: Contains all the resources necessary for a single dataset

Parameters:
  pPipelineReference:
    Type: String
    Default: none
  pApp:
    Description: Name of the application
    Type: String
    Default: "{{resolve:ssm:/SDLF/Misc/pApp}}"
  pDatasetName:
    Description: The name of the dataset (all lowercase, no symbols or spaces)
    Type: String
    AllowedPattern: "[a-z0-9]{2,14}"
  pEnvironment:
    Description: Environment name
    Type: String
    Default: "{{resolve:ssm:/SDLF/Misc/pEnv}}"
  pOrg:
    Description: Name of the organization owning the datalake
    Type: String
    Default: "{{resolve:ssm:/SDLF/Misc/pOrg}}"
  pStageBucket:
    Description: The stage bucket for the solution
    Type: String
    Default: "{{resolve:ssm:/SDLF/S3/StageBucket}}"
  pTeamName:
    Description: Name of the team owning the pipeline (all lowercase, no symbols or spaces)
    Type: String
    AllowedPattern: "[a-z0-9]*"
  pPipelineDetails: # TODO make it more generic, like pPipelineMetadata
    Type: String
    Default: >-
      {
        "main": {
          "transforms": {
            "stage_A_transform": "light_transform_blueprint",
            "stage_B_transform": "heavy_transform_blueprint"
          }
        }
      }

Resources:
  ######## GLUE #########
  rGlueDataCatalog:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Description: !Sub "${pTeamName} team ${pDatasetName} metadata catalog"
        Name: !Sub ${pOrg}_${pApp}_${pEnvironment}_${pTeamName}_${pDatasetName}_db

  rGlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Role: !Sub "{{resolve:ssm:/SDLF/IAM/${pTeamName}/CrawlerRoleArn:1}}"
      CrawlerSecurityConfiguration: !Sub sdlf-${pTeamName}-glue-security-config
      DatabaseName: !Ref rGlueDataCatalog
      Name: !Sub sdlf-${pTeamName}-${pDatasetName}-post-stage-crawler
      Targets:
        S3Targets:
          - Path: !Sub s3://${pStageBucket}/post-stage/${pTeamName}/${pDatasetName}

  rGlueCrawlerLakeFormationPermissions:
    Type: AWS::LakeFormation::Permissions
    Properties:
      DataLakePrincipal:
        DataLakePrincipalIdentifier: !Sub "{{resolve:ssm:/SDLF/IAM/${pTeamName}/CrawlerRoleArn:1}}"
      Permissions:
        - CREATE_TABLE
        - ALTER
        - DROP
      Resource:
        DatabaseResource:
          Name: !Ref rGlueDataCatalog

  ######## SSM #########
  rGlueDataCatalogSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /SDLF/Glue/${pTeamName}/${pDatasetName}/DataCatalog
      Type: String
      Value: !Ref rGlueDataCatalog
      Description: !Sub "${pTeamName} team ${pDatasetName} metadata catalog"

  rDatasetSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /SDLF/Datasets/${pTeamName}/${pDatasetName}
      Type: String
      Value: !Ref pPipelineDetails # bit of a hack for datasets lambda
      Description: !Sub "Placeholder ${pTeamName} ${pDatasetName}"

Outputs:
  oPipelineReference:
    Description: CodePipeline reference this stack has been deployed with
    Value: !Ref pPipelineReference
  oPipelineTransforms:
    Description: Transforms to put in DynamoDB
    Value: !Ref pPipelineDetails